---
name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy
        uses: AlexxNB/caprover-action@v1
        with:
          server: 'https://captain.caprover.rmargar.net'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'rmargar-website'
