name: Test

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: Run tests
        run: make test

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
           verbose: true
